name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    if: ${{ github.reposity_owner }} == 'Interactions-as-a-Service'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js 16.17
        uses: actions/setup-node@v3
        with:
          node-version: 16.17

      - name: Install Dependencies
        run: npm ci

      - name: Check for formatting issues
        run: npm run check:format

      - name: Check for linting issues
        run: npm run check:lint

      - name: Create Release Pull Request
        uses: changesets/action@v1
        with:
          version: node .github/changeset-version.js
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
